# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'armut-main' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for armut-main
    pod 'Alamofire', '~> 4.4'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SwiftyJSON'



end
